In [1]:
%pylab qt
import cv2
import numpy as np
import matplotlib.pyplot as plt


Populating the interactive namespace from numpy and matplotlib


在OpenCV中使用imread函数时，除了第一个参数外（第一个参数是指定需要读取的图片的路径和图片名），我们还可以指定一个参数，常用的就是"IMREAD_UNCHANGED"、"IMREAD_GRAYSCALE"、"IMREAD_COLOR"三个属性了

1）"IMREAD_UNCHANGED"指定用图片的原来格式打开，即以不改变图片的方式打开，图片是彩色就是彩色，图片是灰度图像就是灰度图像

2）"IMREAD_GRAYSCALE"指定用灰度图像的方式打开图片，即将原始图像转化为灰度图像再打开

3）"IMREAD_COLOR"指定用彩色图像打开图片

In [2]:
#grayscale 中gray是灰色的意思 grayscale 会把alpha部分移除，
# alpha是透明度的值， 在jpg里面包含了4个值，bgra bgr是3个颜色的缩写
img = cv2.imread('image.jpg', cv2.IMREAD_GRAYSCALE) 
print(img)

[[138 139 140 ... 157 155 154]
 [138 140 141 ... 157 155 155]
 [139 141 142 ... 157 155 154]
 ...
 [143 143 145 ...  90  88  88]
 [143 143 145 ...  90  89  89]
 [142 143 145 ...  90  89  89]]


# 这里有两个图片显示的选项，一个是用cv2.imshow() 一个是用 plt.show()

In [ ]:
cv2.imshow('image', img)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [7]:
plt.imshow(img, cmap='gray', interpolation='bicubic')
plt.plot([50,100],[50,100],'r',linewidth=5)
plt.show()